name: hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo statement
        run: | 
          echo "Hello world01"
          echo "Hellow world02"
