name: hello world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "A demo build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build test
        run: echo "A demo test"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build deploy
        run: echo "A demo deploy"

