name: Env_Demo
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env_demo:
    env:
      APP_ENV: "test"
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to dev
        run: echo "APP is connecting to $APP_ENV"
